-- Migration: Create MGE (Mightiest Governor Event) tables
-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)

-- MGE Events
CREATE TABLE IF NOT EXISTS public.mge_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_date date NOT NULL,
  focused_commander text NOT NULL,
  notes text,
  is_published boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS mge_events_date_idx ON public.mge_events(event_date DESC);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION public.mge_events_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS mge_events_updated_at_trigger ON public.mge_events;
CREATE TRIGGER mge_events_updated_at_trigger
  BEFORE UPDATE ON public.mge_events
  FOR EACH ROW EXECUTE FUNCTION public.mge_events_updated_at();

-- MGE Selections (who is assigned to which ranking tier)
CREATE TABLE IF NOT EXISTS public.mge_selections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mge_event_id bigint NOT NULL REFERENCES public.mge_events(id) ON DELETE CASCADE,
  member_name text NOT NULL,
  ranking_tier text NOT NULL DEFAULT 'Top 10',
  power_cap bigint,
  reason text,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),

  UNIQUE(mge_event_id, member_name)
);

CREATE INDEX IF NOT EXISTS mge_selections_event_idx ON public.mge_selections(mge_event_id);

-- RLS: public read/write (admin gated at UI level)
ALTER TABLE public.mge_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mge_selections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read" ON public.mge_events FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.mge_events FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.mge_events FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.mge_events FOR DELETE USING (true);

CREATE POLICY "Allow public read" ON public.mge_selections FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.mge_selections FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.mge_selections FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.mge_selections FOR DELETE USING (true);
