-- Seed data for apply_commanders. Regenerate with:
--   node scripts/build-apply-commanders-sql.mjs
--
-- Idempotent: uses INSERT ... ON CONFLICT (id) DO UPDATE so re-running with a
-- refreshed txt just applies the diff. Legacy ids from the TS archive are
-- preserved where names match, keeping past leader_applications lookups alive.

insert into public.apply_commanders (id, name, specialties, rarity, image_url, sort_order) values
  ('achilles', 'Achilles', ARRAY['Cavalry','Versatility','Combo']::text[], 'legendary', null, 0),
  ('aethelflaed', 'Aethelflaed', ARRAY['Leadership','Peacekeeping','Support']::text[], null, null, 1),
  ('afonso', 'Afonso', ARRAY['Engineering','Versatility','Support']::text[], null, null, 2),
  ('alexander-nevs', 'Alexander Nevs', ARRAY['Cavalry','Versatility','Skill']::text[], null, null, 3),
  ('alexander-the-great', 'Alexander the Great', ARRAY['Infantry','Versatility','Attack']::text[], 'legendary', null, 4),
  ('alp-arslan', 'Alp Arslan', ARRAY['Archer','Versatility','Skill']::text[], 'legendary', null, 5),
  ('archimedes', 'Archimedes', ARRAY['Engineering','Versatility','Defense']::text[], 'legendary', null, 6),
  ('artemisia', 'Artemisia', ARRAY['Archer','Garrison','Defense']::text[], null, null, 7),
  ('ashurbanipa', 'Ashurbanipa', ARRAY['Archer','Conquering','Skill']::text[], null, null, 8),
  ('attila', 'Attila', ARRAY['Cavalry','Conquering','Attack']::text[], 'legendary', null, 9),
  ('babur', 'Babur', ARRAY['Engineering','Versatility','Attack']::text[], 'legendary', null, 10),
  ('baibars', 'Baibars', ARRAY['Cavalry','Conquering','Skill']::text[], 'epic', null, 11),
  ('bai-qi', 'Bai Qi', ARRAY['Infantry','Versatility','Smite']::text[], 'legendary', null, 12),
  ('belisarius', 'Belisarius', ARRAY['Cavalry','Peacekeeping','Mobility']::text[], 'epic', null, 13),
  ('belisarius-prime', 'Belisarius Prime', ARRAY['Cavalry','Versatility','Mobility']::text[], 'legendary', null, 14),
  ('bertrand', 'Bertrand', ARRAY['Cavalry','Conquering','Defense']::text[], null, null, 15),
  ('bjorn-ironside', 'Bjorn Ironside', ARRAY['Infantry','Conquering','Skill']::text[], null, null, 16),
  ('boudica-prime', 'Boudica Prime', ARRAY['Archer','Versatility','Skill']::text[], 'legendary', null, 17),
  ('cao-cao', 'Cao Cao', ARRAY['Cavalry','Peacekeeping','Mobility']::text[], 'legendary', null, 18),
  ('casimir', 'Casimir', ARRAY['Integration','Gathering','Defense']::text[], null, null, 19),
  ('catherine-de-medici', 'Catherine de’ Medici', ARRAY['Engineering','Versatility','Skill']::text[], null, null, 20),
  ('centurion', 'Centurion', ARRAY['Integration','Gathering','Attack']::text[], null, null, 21),
  ('chandragupta', 'Chandragupta', ARRAY['Cavalry','Conquering','Skill']::text[], null, null, 22),
  ('charlemagne', 'Charlemagne', ARRAY['Leadership','Conquering','Skill']::text[], 'legendary', null, 23),
  ('charles-martel', 'Charles Martel', ARRAY['Infantry','Garrison','Defense']::text[], 'legendary', null, 24),
  ('cheok-jun-gyeong', 'Cheok Jun-Gyeong', ARRAY['Infantry','Versatility','Attack']::text[], 'legendary', null, 25),
  ('choe-yeong', 'Choe Yeong', ARRAY['Archer','Garrison','Defense']::text[], 'legendary', null, 26),
  ('city-keeper', 'City Keeper', ARRAY['Infantry','Versatility','Attack']::text[], null, null, 27),
  ('cleopatra', 'Cleopatra', ARRAY['Integration','Gathering','Support']::text[], null, null, 28),
  ('constance', 'Constance', ARRAY['Integration','Gathering','Skill']::text[], 'elite', null, 29),
  ('constantine', 'Constantine', ARRAY['Infantry','Garrison','Support']::text[], null, null, 30),
  ('cyrus-the-great', 'Cyrus the Great', ARRAY['Archer','Versatility','Attack']::text[], 'legendary', null, 31),
  ('diaochan', 'Diaochan', ARRAY['Integration','Peacekeeping','Support']::text[], 'epic', null, 32),
  ('dido', 'Dido', ARRAY['Archer','Versatility','Skill']::text[], 'legendary', null, 33),
  ('dragon-lancer', 'Dragon Lancer', ARRAY['Cavalry','Peacekeeping','Skill']::text[], null, null, 34),
  ('edward-of-woodstock', 'Edward of Woodstock', ARRAY['Archer','Conquering','Skill']::text[], 'legendary', null, 35),
  ('edward-teach', 'Edward Teach', ARRAY['Leadership','Versatility','Attack']::text[], null, null, 36),
  ('el-cid', 'El Cid', ARRAY['Archer','Garrison','Skill']::text[], 'legendary', null, 37),
  ('emperor-leonidas', 'Emperor Leonidas', ARRAY['Infantry','Garrison','Defense']::text[], null, null, 38),
  ('erik-the-red', 'Erik the Red', ARRAY['Infantry','Conquering','Skill']::text[], null, null, 39),
  ('eskandar', 'Eskandar', ARRAY['Cavalry','Smite','Attack']::text[], null, null, 40),
  ('eulji-mundeok', 'Eulji Mundeok', ARRAY['Infantry','Garrison','Defense']::text[], 'epic', null, 41),
  ('frederick-i', 'Frederick I', ARRAY['Leadership','Integration','Skill']::text[], 'legendary', null, 42),
  ('frederick-ii', 'Frederick II', ARRAY['Engineering','Versatility','Skill']::text[], null, null, 43),
  ('gaius-marius', 'Gaius Marius', ARRAY['Integration','Gathering','Leadership']::text[], 'elite', null, 44),
  ('genghis-khan', 'Genghis Khan', ARRAY['Cavalry','Skill','Attack']::text[], 'legendary', null, 45),
  ('genghis-khan-prime', 'Genghis Khan Prime', ARRAY['Cavalry','Versatility','Skill']::text[], null, null, 46),
  ('gilgamesh', 'Gilgamesh', ARRAY['Archer','Skill','Conquering']::text[], 'legendary', null, 47),
  ('gorgo', 'Gorgo', ARRAY['Infantry','Versatility','Defense']::text[], 'legendary', null, 48),
  ('guan-yu', 'Guan Yu', ARRAY['Infantry','Skill','Versatility']::text[], 'legendary', null, 49),
  ('guan-yu-prime', 'Guan Yu Prime', ARRAY['Infantry','Versatility','Smite']::text[], null, null, 50),
  ('hannibal-barca', 'Hannibal Barca', ARRAY['Leadership','Conquering','Attack']::text[], 'legendary', null, 51),
  ('harald-sigurdsson', 'Harald Sigurdsson', ARRAY['Infantry','Conquering','Skill']::text[], 'legendary', null, 52),
  ('hermann', 'Hermann', ARRAY['Archer','Garrison','Skill']::text[], 'epic', null, 53),
  ('hermann-prime', 'Hermann Prime', ARRAY['Archer','Versatility','Skill']::text[], 'legendary', null, 54),
  ('honda-tadakatsu', 'Honda Tadakatsu', ARRAY['Cavalry','Mobility','Skill']::text[], 'legendary', null, 55),
  ('huo-qubing', 'Huo Qubing', ARRAY['Cavalry','Mobility','Skill']::text[], 'legendary', null, 56),
  ('imhotep', 'Imhotep', ARRAY['Archer','Integration','Skill']::text[], 'legendary', null, 57),
  ('ishida-mitsunari', 'Ishida Mitsunari', ARRAY['Integration','Gathering','Skill']::text[], 'legendary', null, 58),
  ('jadwiga', 'Jadwiga', ARRAY['Leadership','Garrison','Support']::text[], 'legendary', null, 59),
  ('jan-zizka', 'Jan Zizka', ARRAY['Leadership','Garrison','Defense']::text[], 'legendary', null, 60),
  ('julius-caesar', 'Julius Caesar', ARRAY['Leadership','Gathering','Attack']::text[], 'legendary', null, 61),
  ('joan-of-arc', 'Joan of Arc', ARRAY['Integration','Gathering','Support']::text[], 'epic', null, 62),
  ('joan-of-arc-prime', 'Joan of Arc Prime', ARRAY['Leadership','Support','Skill']::text[], 'legendary', null, 63),
  ('john-hunyadi', 'John Hunyadi', ARRAY['Cavalry','Versatility','Attack']::text[], 'legendary', null, 64),
  ('julius-caesar-prime', 'Julius Caesar Prime', ARRAY['Leadership','Versatility','Support']::text[], null, null, 65),
  ('kusunoki-masashige', 'Kusunoki Masashige', ARRAY['Archer','Garrison','Skill']::text[], 'epic', null, 66),
  ('lancelot', 'Lancelot', ARRAY['Cavalry','Mobility','Skill']::text[], 'elite', null, 67),
  ('liu-che', 'Liu Che', ARRAY['Archer','Skill','Versatility']::text[], 'legendary', null, 68),
  ('lohar', 'Lohar', ARRAY['Integration','Peacekeeping','Attack']::text[], 'epic', null, 69),
  ('lu-bu', 'Lu Bu', ARRAY['Cavalry','Skill','Attack']::text[], 'legendary', null, 70),
  ('lu-xun', 'Lu Xun', ARRAY['Archer','Versatility','Skill']::text[], null, null, 71),
  ('mahatma-gandhi', 'Mahatma Gandhi', ARRAY['Integration','Gathering','Support']::text[], null, null, 72),
  ('mehmed-ii', 'Mehmed II', ARRAY['Leadership','Conquering','Skill']::text[], 'legendary', null, 73),
  ('merlin', 'Merlin', ARRAY['Leadership','Support','Skill']::text[], null, null, 74),
  ('minamoto-no-yoshitsune', 'Minamoto no Yoshitsune', ARRAY['Cavalry','Peacekeeping','Skill']::text[], 'legendary', null, 75),
  ('miyamoto-musashi', 'Miyamoto Musashi', ARRAY['Infantry','Skill','Attack']::text[], null, null, 76),
  ('mulan', 'Mulan', ARRAY['Leadership','Support','Skill']::text[], 'legendary', null, 77),
  ('nevsky-prime', 'Nevsky Prime', ARRAY['Cavalry','Smite','Skill']::text[], null, null, 78),
  ('nobunaga-oda', 'Nobunaga Oda', ARRAY['Archer','Skill','Attack']::text[], null, null, 79),
  ('osman-i', 'Osman I', ARRAY['Leadership','Skill','Attack']::text[], 'epic', null, 80),
  ('pakal-ii', 'Pakal II', ARRAY['Infantry','Versatility','Defense']::text[], null, null, 81),
  ('pelagius', 'Pelagius', ARRAY['Cavalry','Skill','Defense']::text[], 'epic', null, 82),
  ('pericles', 'Pericles', ARRAY['Infantry','Garrison','Support']::text[], 'legendary', null, 83),
  ('philip-ii', 'Philip II', ARRAY['Leadership','Garrison','Defense']::text[], 'legendary', null, 84),
  ('pyrrhus', 'Pyrrhus', ARRAY['Infantry','Skill','Defense']::text[], null, null, 85),
  ('ramesses-ii', 'Ramesses II', ARRAY['Archer','Versatility','Defense']::text[], 'legendary', null, 86),
  ('ragnar-lodbrok', 'Ragnar Lodbrok', ARRAY['Leadership','Conquering','Attack']::text[], 'legendary', null, 87),
  ('richard-i', 'Richard I', ARRAY['Infantry','Garrison','Defense']::text[], 'legendary', null, 88),
  ('rokhlin', 'Rokhlin', ARRAY['Infantry','Skill','Attack']::text[], null, null, 89),
  ('saladin', 'Saladin', ARRAY['Cavalry','Integration','Skill']::text[], 'legendary', null, 90),
  ('scipio-africanus', 'Scipio Africanus', ARRAY['Leadership','Conquering','Attack']::text[], 'epic', null, 91),
  ('scipio-prime', 'Scipio Africanus Prime', ARRAY['Leadership','Versatility','Skill']::text[], 'legendary', null, 92),
  ('seondeok', 'Seondeok', ARRAY['Integration','Gathering','Support']::text[], 'legendary', null, 93),
  ('shao-kahn', 'Shao Kahn', ARRAY['Leadership','Attack','Skill']::text[], null, null, 94),
  ('shajar-al-durr', 'Shajar al-Durr', ARRAY['Integration','Gathering','Support']::text[], 'legendary', null, 95),
  ('siegfried', 'Siegfried', ARRAY['Infantry','Smite','Defense']::text[], null, null, 96),
  ('sokrates', 'Sokrates', ARRAY['Leadership','Support','Skill']::text[], null, null, 97),
  ('suleiman-i', 'Suleiman I', ARRAY['Leadership','Conquering','Skill']::text[], 'legendary', null, 98),
  ('sun-tzu', 'Sun Tzu', ARRAY['Infantry','Garrison','Skill']::text[], 'epic', null, 99),
  ('takeda-shingen', 'Takeda Shingen', ARRAY['Cavalry','Skill','Mobility']::text[], 'legendary', null, 100),
  ('tariq-ibn-ziyad', 'Tariq ibn Ziyad', ARRAY['Infantry','Versatility','Skill']::text[], 'legendary', null, 101),
  ('theodora', 'Theodora', ARRAY['Leadership','Garrison','Support']::text[], 'legendary', null, 102),
  ('theodora-prime', 'Theodora Prime', ARRAY['Leadership','Garrison','Skill']::text[], null, null, 103),
  ('thutmose-iii', 'Thutmose III', ARRAY['Archer','Skill','Attack']::text[], 'legendary', null, 104),
  ('tomoe-gozen', 'Tomoe Gozen', ARRAY['Archer','Integration','Skill']::text[], 'elite', null, 105),
  ('trajan', 'Trajan', ARRAY['Leadership','Support','Integration']::text[], 'legendary', null, 106),
  ('trajan-prime', 'Trajan Prime', ARRAY['Leadership','Versatility','Support']::text[], null, null, 107),
  ('tutus', 'Tutus', ARRAY['Engineering','Defense','Versatility']::text[], null, null, 108),
  ('william-i', 'William I', ARRAY['Archer','Versatility','Attack']::text[], 'legendary', null, 109),
  ('william-wallace', 'William Wallace', ARRAY['Infantry','Versatility','Attack']::text[], 'legendary', null, 110),
  ('wu-zetian', 'Wu Zetian', ARRAY['Leadership','Garrison','Support']::text[], 'legendary', null, 111),
  ('xiang-yu', 'Xiang Yu', ARRAY['Cavalry','Conquering','Skill']::text[], 'legendary', null, 112),
  ('yi-seong-gye', 'Yi Seong Gye', ARRAY['Archer','Garrison','Garrison']::text[], 'legendary', null, 113),
  ('yi-sun-sin', 'Yi Sun-Sin', ARRAY['Leadership','Garrison','Defense']::text[], 'legendary', null, 114),
  ('zenobia', 'Zenobia', ARRAY['Infantry','Garrison','Support']::text[], 'legendary', null, 115),
  ('zhuge-liang', 'Zhuge Liang', ARRAY['Archer','Skill','Versatility']::text[], 'legendary', null, 116)
on conflict (id) do update set
  name = excluded.name,
  specialties = excluded.specialties,
  rarity = excluded.rarity,
  image_url = excluded.image_url,
  sort_order = excluded.sort_order,
  updated_at = now();
